name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
env:
  REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm build --if-present

      - uses: reviewdog/action-setup@v1
      - run: npm run lint | reviewdog -f=eslint -reporter=github-check

      - run: npm run test:coverage
      - uses: codecov/codecov-action@v1

